apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-distroless
  annotations:
    chains.tekton.dev/transparency-upload: "true"
    description: |
      Takes in the distroless repo as an input and builds & pushes distroless images.
spec:
  params:
    - name: PROJECT_ID
      type: string
      default: distroless
    - name: CHAINS-GIT_COMMIT
      type: string
    - name: CHAINS-GIT_URL
      type: string
      default: https://github.com/GoogleContainerTools/distroless
  workspaces:
  - name: source
    mountPath: /go/src/github.com/GoogleContainerTools/distroless
  steps:
    - name: bazel
      image: gcr.io/cloud-marketplace-containers/google/bazel:3.4.1
      workingDir: $(workspaces.source.path)
      env:
      - name: PROJECT_ID
        value: $(params.PROJECT_ID)
      - name: REGISTRY
        value: insecure-registry.default.svc.cluster.local:5000
      - name: COMMIT_SHA
        value: $(params.CHAINS-GIT_COMMIT)
      script: |
        #!/bin/sh
        set -ex

        # Make sure python points to python3
        update-alternatives --install /usr/bin/python python /usr/bin/python3 0

        bazel build //package_manager:dpkg_parser.par

        bazel build --jobs=1 @package_bundle_amd64_debian10//file:packages.bzl
        bazel build --jobs=1 @package_bundle_arm_debian10//file:packages.bzl
        bazel build --jobs=1 @package_bundle_arm64_debian10//file:packages.bzl
        bazel build --jobs=1 @package_bundle_s390x_debian10//file:packages.bzl
        bazel build --jobs=1 @package_bundle_ppc64le_debian10//file:packages.bzl
        bazel build --jobs=1 @package_bundle_amd64_debian11//file:packages.bzl
        bazel build --jobs=1 @package_bundle_arm_debian11//file:packages.bzl
        bazel build --jobs=1 @package_bundle_arm64_debian11//file:packages.bzl
        bazel build --jobs=1 @package_bundle_s390x_debian11//file:packages.bzl
        bazel build --jobs=1 @package_bundle_ppc64le_debian11//file:packages.bzl

        bazel build all.tar
        
        # install jq and create the images file
        ./cloudbuild_jq.sh

        bazel run //:publish


