apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: distroless-provenance
  annotations:
    chains.tekton.dev/transparency-upload: "true"
    description: |
      Generates provenance for the distroless repo
spec:
  params:
  - name: PROJECT_ID
    type: string
    default: distroless
  - name: CHAINS-GIT_COMMIT
    type: string
  - name: CHAINS-GIT_URL
    type: string
    default: https://github.com/GoogleContainerTools/distroless
  workspaces:
  - name: workarea
    description: The workspace where the repo will be cloned.
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: workarea
      subpath: git
    params:
    - name: url
      value: $(params.CHAINS-GIT_URL)
    - name: revision
      value: $(params.CHAINS-GIT_COMMIT)
  - name: build-distroless
    runAfter: [git-clone]
    taskRef:
      name: build-distroless
    params:
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-0
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "0"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-1
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "1"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-2
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "2"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-3
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "3"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-4
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "4"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-5
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "5"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-6
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "6"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
  - name: provenance-7
    runAfter: [build-distroless]
    taskRef:
      name: distroless-provenance
    params:
    - name: MANIFEST_SUBSECTION
      value: "7"
    workspaces:
    - name: source
      workspace: workarea
      subpath: git
